 var participantes = [
    {nome: 'Tony',senha: 'tony2531'},
    {nome: 'Alexsandra',senha: 'alex4226'},
    {nome: 'Duda', amigoProibido:'Alexsandra',senha: 'duda3647'},
    {nome: 'Antonia',senha: 'anto1638'},
    {nome: 'Samara',senha: 'sama6387'},
    {nome: 'Douglas',senha: 'doug7529'},
    {nome: 'Ana Paula',senha: 'anap6360'},
    {nome: 'Alex',senha: 'alex3807'},
    {nome: 'Cristina',senha: 'cris9648'},
    {nome: 'Isabela', amigoProibido:'Cristina',senha: 'isab7164'},
    {nome: 'Salma',senha: 'salm1400'},
    {nome: 'Alexandre',senha: 'alex3976'},
    {nome: 'Bianca', amigoProibido:'Salma',senha: 'bian7653'},
    {nome: 'Camila', amigoProibido:'Salma',senha: 'cami2780'},
    {nome: 'Helio',senha: 'heli3541'},
    {nome: 'Amanda',senha: 'amand63501'},
    {nome: 'Felipe',senha: 'feli4831'},
    {nome: 'Sara',senha: 'sara2718'},
    {nome: 'Milena',senha: 'mile6423'}
];
