 var participantes = [
    {nome: 'Tony',senha: 'tony2531'},
    {nome: 'Alexsandra',senha: 'alex4226'},
    {nome: 'Duda',senha: 'duda3647'},
    {nome: 'Gabi', amigoProibido:'Alexsandra',senha: 'gabi4695'},
    {nome: 'Alex',senha: 'alex3807'},
    {nome: 'Cristina',senha: 'cris9648'},
    {nome: 'Isabela', amigoProibido:'Cristina',senha: 'isab7164'},
    {nome: 'Lucas', amigoProibido:'Cristina',senha: 'luca7122'},
    {nome: 'Miguel', amigoProibido:'Cristina',senha: 'migu3247'},
    {nome: 'Sonia', amigoProibido:'Cristina',senha: 'soni9999'},
    {nome: 'Salma',senha: 'salm9400'},
    {nome: 'Alexandre',senha: 'alex3976'},
    {nome: 'Bianca', senha: 'bian7653'},
    {nome: 'Camila', amigoProibido:'Salma',senha: 'cami2780'},
    {nome: 'Helio',senha: 'heli3541'},
    {nome: 'Valeria',senha: 'vale5246'},
    {nome: 'Amanda',senha: 'aman63501'},
    {nome: 'Felipe',senha: 'feli4831'},
    {nome: 'Milena',senha: 'mile6423'}
];
